main: me.often.aureliummobs.Main
name: AureliumMobs
author: _OfTeN_
version: 1.14
api-version: 1.16
depend:
  - AureliumSkills
softdepend:
  - PlaceholderAPI
  - WorldGuard
commands:
  aureliummobs:
    aliases: [amobs, am]
